const jokes = [
    {
        id: "excessive-compliment",
        name: "Excessive Compliment",
        category: "Game Related",
        era: "2020-2022",
        status: "Inanimate",
        color: "Rainbow",
        rating: "3",
        image: "pics/ec.gif",
    },
    {
        id: "naruto-german-opening",
        name: "Naruto German Opening",
        category: "Song",
        era: "2020-2022",
        status: "Inanimate",
        color: "Orange",
        rating: "0",
        image: "pics/naruto.png",
    },
    {
        id: "confirmed-thrills",
        name: "Confirmed Thrills",
        category: "Song",
        era: "2020-2022",
        status: "Inanimate",
        color: "Red",
        rating: "3",
        image: "pics/thrills.png",
    },
        {
        id: "the-hill",
        name: "The Hill",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Green",
        rating: "3",
        image: "pics/hill.png",
    },
        {
        id: "it-feels-good-sir",
        name: "It feels good sir",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Green",
        rating: "4",
        image: "pics/itfeels.jpg",
    },
        {
        id: "bro-why",
        name: "Bro why did you pick that up?",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Blue",
        rating: "3",
        image: "pics/why.png",
    },
        {
        id: "jolly-is-gay",
        name: "Jolly is gay",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Gray",
        rating: "5",
        image: "pics/jolly.png",
    },
        {
        id: "luck-is-gay",
        name: "Luck is gay",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Gray",
        rating: "5",
        image: "pics/luckgay.png",
    },
        {
        id: "jfk-bit",
        name: "Five intro bit",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Red",
        rating: "1000000",
        image: "pics/five.jpg",
    },
        {
        id: "lpe",
        name: "LPE Edition",
        category: "Thing/Idea",
        era: "2025-present",
        status: "Inanimate",
        color: "Blue",
        rating: "4",
        image: "pics/lpe.png",
    },
        {
        id: "three-star",
        name: "Another three star photo",
        category: "Quote/Moment",
        era: "2023-2024",
        status: "Inanimate",
        color: "Black",
        rating: "3",
        image: "pics/three.png",
    },
        {
        id: "are-you-sure",
        name: "Ok so he's cheating. Are you sure?",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Brown",
        rating: "3",
        image: "pics/areyou.png",
    },
    {
        id: "peggy-fortnite",
        name: "Peggyyyyyy Fortniteeee",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Gray",
        rating: "3",
        image: "pics/fortnite.png",
    },
    {
        id: "a-hee-hee",
        name: "A hee hee",
        category: "Quote/Moment",
        era: "2023-2024",
        status: "Inanimate",
        color: "Brown",
        rating: "2",
        image: "pics/bacon.png",
    },
    {
        id: "dl-leaner",
        name: "Who is DL Leaner?",
        category: "Quote/Moment",
        era: "2023-2024",
        status: "Inanimate",
        color: "Black",
        rating: "3",
        image: "pics/dl.png",
    },
    {
        id: "new-school",
        name: "Its your last chance in new school",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Purple",
        rating: "-1000000",
        image: "pics/newschool.jpg",
    },
    {
        id: "outlannad",
        name: "Outlannad",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Green",
        rating: "5",
        image: "pics/outlannad.png",
    },
    {
        id: "oucher",
        name: "Oucher",
        category: "Song",
        era: "2025-present",
        status: "Inanimate",
        color: "Gray",
        rating: "5",
        image: "pics/oucher.png",
    },
    {
        id: "tuesday",
        name: "Tradeup Tuesday",
        category: "Thing/Idea",
        era: "2025-present",
        status: "Inanimate",
        color: "Purple",
        rating: "4",
        image: "pics/tradeup.png",
    },
    {
        id: "gabe",
        name: "Gabe",
        category: "Person",
        era: "2020-2022",
        status: "Alive",
        color: "White",
        rating: "0",
        image: "pics/gabe.png",
    },
    {
        id: "dev",
        name: "Dev",
        category: "Person",
        era: "2025-present",
        status: "Alive",
        color: "White",
        rating: "5",
        image: "pics/dev.png",
    },
    {
        id: "sky",
        name: "Sky",
        category: "Person",
        era: "2023-2024",
        status: "Alive",
        color: "White",
        rating: "1",
        image: "pics/sky.png",
    },
    {
        id: "mcridemonday",
        name: "MC Ride Mondays",
        category: "Thing/Idea",
        era: "2023-2024",
        status: "Inanimate",
        color: "Gray",
        rating: "2",
        image: "pics/mcride.gif",
    },
    {
        id: "kino",
        name: "Kino Der Toten Black Ops 1",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Gray",
        rating: "2",
        image: "pics/kino.jpg",
    },
    {
        id: "spaceland",
        name: "Zombies in Spaceland",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Pink",
        rating: "4",
        image: "pics/spaceland.jpg",
    },
    {
        id: "lucy",
        name: "Lucy Bedroque",
        category: "Person",
        era: "2025-present",
        status: "Alive",
        color: "Pink",
        rating: "5",
        image: "pics/lucy.png",
    },
    {
        id: "luci",
        name: "Luci Mouker",
        category: "Person",
        era: "2025-present",
        status: "Alive",
        color: "Purple",
        rating: "5",
        image: "pics/luci.png",
    },
    {
        id: "jfk",
        name: "John F. Kennedy",
        category: "Person",
        era: "2025-present",
        status: "Dead",
        color: "White",
        rating: "2",
        image: "pics/jfk.jpg",
    },
    {
        id: "reagan",
        name: "Ronald Reagan",
        category: "Person",
        era: "2023-2024",
        status: "Dead",
        color: "White",
        rating: "0",
        image: "pics/reagan.jpg",
    },
    {
        id: "jeff",
        name: "Jeff Epstein",
        category: "Person",
        era: "2025-present",
        status: "In Limbo",
        color: "White",
        rating: "-1000000",
        image: "pics/jeff.png",
    },
    {
        id: "inga9",
        name: "Inga 9",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Blue",
        rating: "1",
        image: "pics/inga9.png",
    },
    {
        id: "bernorn",
        name: "Bernorn",
        category: "Person",
        era: "2020-2022",
        status: "Dead",
        color: "Green",
        rating: "2",
        image: "pics/bernorn.png",
    },
    {
        id: "takeo",
        name: "Takeo",
        category: "Person",
        era: "2025-present",
        status: "Alive (fictitious)",
        color: "Green",
        rating: "4",
        image: "pics/takeo.jpg",
    },
    {
        id: "richtofen",
        name: "Richtofen",
        category: "Person",
        era: "2025-present",
        status: "Alive (fictitious)",
        color: "Brown",
        rating: "4",
        image: "pics/richtofen.jpg",
    },
    {
        id: "nikolai",
        name: "Nikolai",
        category: "Person",
        era: "2025-present",
        status: "Alive (fictitious)",
        color: "Brown",
        rating: "4",
        image: "pics/nikolai.png",
    },
    {
        id: "subaru",
        name: "Natsuki Subaru",
        category: "Person",
        era: "2020-2022",
        status: "In Limbo",
        color: "Orange",
        rating: "2",
        image: "pics/aura.png",
    },
    {
        id: "enid",
        name: "Enid Sinclair",
        category: "Person",
        era: "2025-present",
        status: "Alive (fictitious)",
        color: "Purple",
        rating: "4",
        image: "pics/enid.png",
    },
    {
        id: "devin",
        name: "Devin",
        category: "Person",
        era: "2023-2024",
        status: "Alive",
        color: "Blue",
        rating: "1",
        image: "pics/devin.png",
    },
    {
        id: "tomoyo",
        name: "Tomoyo Sakagami",
        category: "Person",
        era: "2025-present",
        status: "Alive (fictitious)",
        color: "Gray",
        rating: "4",
        image: "pics/tomoyo.png",
    },
    {
        id: "nagisa",
        name: "Nagisa Furukawa",
        category: "Person",
        era: "2025-present",
        status: "Dead (fictitious)",
        color: "Brown",
        rating: "4",
        image: "pics/nagisa.png",
    },
    {
        id: "kyou",
        name: "Kyou Fujibayashi",
        category: "Person",
        era: "2025-present",
        status: "Alive (fictitious)",
        color: "Purple",
        rating: "2",
        image: "pics/yvl.jpg",
    },
    {
        id: "tsunderes",
        name: "A tsundere",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Red",
        rating: "-1000000",
        image: "pics/tsundere.png",
    },
    {
        id: "mookie",
        name: "Mookie Betts",
        category: "Person",
        era: "2023-2024",
        status: "Alive",
        color: "Red",
        rating: "5",
        image: "pics/mookie.jpg",
    },
    {
        id: "jarren",
        name: "Jarren Duran",
        category: "Person",
        era: "2023-2024",
        status: "Alive",
        color: "Red",
        rating: "0",
        image: "pics/jarren.png",
    },
    {
        id: "joe",
        name: "Joe Bart",
        category: "Person",
        era: "2025-present",
        status: "Alive",
        color: "White",
        rating: "5",
        image: "pics/joe.jpg",
    },
    {
        id: "mark",
        name: "Mark Zuckerburg Video",
        category: "Thing/Idea",
        era: "2025-present",
        status: "Inanimate",
        color: "Gray",
        rating: "4",
        image: "pics/mark.jpg",
    },
    {
        id: "yankees-parking",
        name: "Yankees Parking Only Sign",
        category: "Thing/Idea",
        era: "2023-2024",
        status: "Inanimate",
        color: "Blue",
        rating: "0",
        image: "pics/yankees.jpg",
    },
    {
        id: "bb",
        name: "Bloodbath",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Red",
        rating: "3",
        image: "pics/Bloodbath.png",
    },
    {
        id: "mrcala",
        name: "Mr. Cala",
        category: "Person",
        era: "2020-2022",
        status: "Dead",
        color: "Blue",
        rating: "3",
        image: "pics/cala.jpg",
    },
    {
        id: "cata",
        name: "Cataclysm",
        category: "Game Related",
        era: "2020-2022",
        status: "Inanimate",
        color: "Orange",
        rating: "2",
        image: "pics/cataclysm.jpg",
    },
    {
        id: "than",
        name: "Thanatophobia",
        category: "Game Related",
        era: "2020-2022",
        status: "Inanimate",
        color: "Black",
        rating: "1",
        image: "pics/than.png",
    },
    {
        id: "blackblizzard",
        name: "Black Blizzard",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Black",
        rating: "4",
        image: "pics/bb.jpg",
    },
    {
        id: "ssoh",
        name: "SSOH",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Red",
        rating: "4",
        image: "pics/ssoh.png",
    },
    {
        id: "icedcave",
        name: "Icedcave",
        category: "Person",
        era: "2020-2022",
        status: "Alive",
        color: "White",
        rating: "4",
        image: "pics/icedcave.png",
    },
    {
        id: "yourmom",
        name: "Your Mom Anime",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Orange",
        rating: "0",
        image: "pics/yourmom.jpg",
    },
    {
        id: "shallot",
        name: "Shallot",
        category: "Person",
        era: "2023-2024",
        status: "Alive",
        color: "White",
        rating: "1",
        image: "pics/shallot.png",
    },
    {
        id: "dan",
        name: "Dan",
        category: "Person",
        era: "2025-present",
        status: "Alive",
        color: "Gray",
        rating: "4",
        image: "pics/dan.png",
    },
    {
        id: "goryo",
        name: "Goryo",
        category: "Game Related",
        era: "2023-2024",
        status: "Dead (fictitious)",
        color: "Gray",
        rating: "1",
        image: "pics/goryo.jpg",
    },
    {
        id: "ohnepixel",
        name: "Ohnepixel",
        category: "Person",
        era: "2025-present",
        status: "Alive",
        color: "Gold",
        rating: "4",
        image: "pics/ohne.jpg",
    },
    {
        id: "sableye",
        name: "Sableye",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Purple",
        rating: "5",
        image: "pics/sableye.jpg",
    },
    {
        id: "wydd",
        name: "Who's your Daddy?",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Blue",
        rating: "3",
        image: "pics/wyd.jpg",
    },
    {
        id: "codiw",
        name: "Call of Duty Infinite Warfare",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Yellow",
        rating: "4",
        image: "pics/iw.jpg",
    },
    {
        id: "codbo2",
        name: "Call of Duty Black Ops 2",
        category: "Game Related",
        era: "2023-2024",
        status: "Inanimate",
        color: "Orange",
        rating: "5",
        image: "pics/bo2.jpg",
    },
    {
        id: "goon",
        name: "I'm Gooning, I'm Gooning!",
        category: "Quote/Moment",
        era: "2023-2024",
        status: "Inanimate",
        color: "Blue",
        rating: "3",
        image: "pics/goon.png",
    },
    {
        id: "amanda",
        name: "Amanda Outlast",
        category: "Game Related",
        era: "2025-present",
        status: "Dead (fictitious)",
        color: "Black",
        rating: "3",
        image: "pics/amanda.png",
    },
    {
        id: "nepsa",
        name: "Nepsa",
        category: "Thing/Idea",
        era: "2025-present",
        status: "Inanimate",
        color: "Brown",
        rating: "3",
        image: "pics/nepsa.png",
    },
    {
        id: "joeim",
        name: "Joe I'm Gay Can You Come Help Me Out?",
        category: "Quote/Moment",
        era: "2025-Present",
        status: "Inanimate",
        color: "Black",
        rating: "3",
        image: "pics/gayjoe.png",
    },
    {
        id: "scotus",
        name: "SCOTUS",
        category: "Thing/Idea",
        era: "2023-2024",
        status: "Inanimate",
        color: "White",
        rating: "1",
        image: "pics/scotus.jpeg",
    },
    {
        id: "tuyu",
        name: "TUYU",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Blue",
        rating: "2",
        image: "pics/tuyu.jpg",
    },
    {
        id: "inanotherworld",
        name: "In another world with my smartphone",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Black",
        rating: "-15",
        image: "pics/smartphone.png",
    },
    {
        id: "giritina",
        name: "Yeule's Giratina",
        category: "Game Related",
        era: "2025-present",
        status: "Dead (fictitious)",
        color: "Gray",
        rating: "4",
        image: "pics/giratina.png",
    },
    {
        id: "schoology",
        name: "Is Schoology down?",
        category: "Quote/Moment",
        era: "2020-2022",
        status: "Inanimate",
        color: "Gray",
        rating: "3",
        image: "pics/schoology.png",
    },
    {
        id: "satanic",
        name: "Satanic age gap",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Blue",
        rating: "3",
        image: "pics/satanic.jpg",
    },
    {
        id: "oreate",
        name: "Oreate",
        category: "Person",
        era: "2020-2022",
        status: "Unknown",
        color: "White",
        rating: "5",
        image: "pics/oreate.jpg",
    },
    {
        id: "part",
        name: "Shitty part in shitty level because people are blackmailing me for it",
        category: "Game Related",
        era: "2020-2022",
        status: "Inanimate",
        color: "Blue",
        rating: "3",
        image: "pics/kissme.png",
    },
    {
        id: "pkpart",
        name: "Prokiller Optation part",
        category: "Game Related",
        era: "2020-2022",
        status: "Inanimate",
        color: "Purple",
        rating: "3",
        image: "pics/pk.png",
    },
    {
        id: "pkgmd",
        name: "ProkillerGMD",
        category: "Person",
        era: "2020-2022",
        status: "Alive",
        color: "Green",
        rating: "-32678945",
        image: "pics/pkgmd.png",
    },
    {
        id: "lbf",
        name: "Luck but Festive",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Yellow",
        rating: "2",
        image: "pics/festive.png",
    },
    {
        id: "yodawg77",
        name: "Yodawg77",
        category: "Person",
        era: "2020-2022",
        status: "Dead",
        color: "Black",
        rating: "3",
        image: "pics/yodawg.png",
    },
    {
        id: "rigv",
        name: "Rigv",
        category: "Person",
        era: "2020-2022",
        status: "Alive",
        color: "Brown",
        rating: "1",
        image: "pics/rigv.jpg",
    },
    {
        id: "pawjob",
        name: "Pawjob",
        category: "Thing/Idea",
        era: "2025-present",
        status: "Inanimate",
        color: "Brown",
        rating: "5",
        image: "pics/pawjob.png",
    },
    {
        id: "kissme",
        name: "Kiss Me Kiss You",
        category: "Game Related",
        era: "2020-2022",
        status: "Inanimate",
        color: "Blue",
        rating: "2",
        image: "pics/kiss.png",
    },
    {
        id: "ch",
        name: "Collab Hub",
        category: "Thing/Idea",
        era: "2020-2022",
        status: "Inanimate",
        color: "Red",
        rating: "3",
        image: "pics/ch.png",
    },
    {
        id: "tai",
        name: "Tai Pen Chat",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Black",
        rating: "4",
        image: "pics/tai.png",
    },
    {
        id: "slaythe",
        name: "Slay the Princess",
        category: "Game Related",
        era: "2023-2024",
        status: "Inanimate",
        color: "White",
        rating: "4",
        image: "pics/slay.jpg",
    },
    {
        id: "curse",
        name: "Curse of Ra",
        category: "Thing/Idea",
        era: "2023-2024",
        status: "Inanimate",
        color: "Beige",
        rating: "3",
        image: "pics/ra.jpg",
    },
    {
        id: "cryo",
        name: "Cryo Gun Gooning",
        category: "Game Related",
        era: "2023-2024",
        status: "Inanimate",
        color: "Blue",
        rating: "0",
        image: "pics/cryo.png",
    },
    {
        id: "poop",
        name: "Poop Gem",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Shit",
        rating: "3",
        image: "pics/poop.png",
    },
    {
        id: "cripple",
        name: "Cripple Fade",
        category: "Quote/Moment",
        era: "2025-present",
        status: "Inanimate",
        color: "Orange",
        rating: "3",
        image: "pics/cripple.png",
    },
    {
        id: "alien",
        name: "That fucking alien that I hate",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Blue",
        rating: "0",
        image: "pics/alien.png",
    },
    {
        id: "hillserver",
        name: "The Hill Server",
        category: "Thing/Idea",
        era: "2025-present",
        status: "Inanimate",
        color: "Green",
        rating: "4",
        image: "pics/tn.png",
    },
    {
        id: "one",
        name: "Lacing Sunohara with E",
        category: "Game Related",
        era: "2025-present",
        status: "Inanimate",
        color: "Yellow",
        rating: "5",
        image: "pics/sunohara.png",
    }
];

function getDateStr(d = new Date()) { return d.toISOString().slice(0, 10); }
function dayIndex() { return Math.floor(Date.now() / 86400000); }
function pickDailyAnswer() { return jokes[dayIndex() % jokes.length]; }
function pickRandomAnswer(excludeId) {
  const pool = jokes.filter(j => j.id !== excludeId);
  const source = pool.length ? pool : jokes;
  return source[Math.floor(Math.random() * source.length)];
}
const DAILY_ANSWER = pickDailyAnswer();
const TODAY = getDateStr();